// src/projects/ui-component/packages/react/src/index.tsx
import * as React from 'react'
import * as common from 'REPOSITORY_NAME'
export * from 'REPOSITORY_NAME'

/**
 * @public
 */
export class ComponentTypeName extends React.Component<{
  data: common.ComponentTypeNameData;
}, {}> {
  render() {
    return (
      <div className='COMPONENT_SHORT_NAME'>
      </div>
    )
  }
}

// src/projects/ui-component/packages/angular/src/index.component.ts
import { Component, Input } from '@angular/core'
import * as common from 'REPOSITORY_NAME'
import { indexTemplateHtml } from './variables'

/**
 * @public
 */
@Component({
  selector: 'COMPONENT_SHORT_NAME',
  template: indexTemplateHtml
})
export class ComponentTypeNameComponent {
  @Input()
  data: common.ComponentTypeNameData
}
