// src/projects/ui-component/packages/angular/demo/main.component.ts
import { Component } from '@angular/core'

import { COMPONENT_TYPE_NAMEData } from '../dist/'

@Component({
  selector: 'app',
  template: `
    <div>
        <a href="https://github.com/AUTHOR/REPOSITORY_NAME/tree/master/packages/angular/demo" target="_blank">the source code of the demo</a>
        <br/>
        <COMPONENT_SHORT_NAME [data]="data">
        </COMPONENT_SHORT_NAME>
    </div>
    `
})
export class MainComponent {
  data: COMPONENT_TYPE_NAME
}

// src/projects/ui-component/packages/react/demo/index.tsx
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import { componentTypeName, componentTypeNameData } from '../dist/'

class Main extends React.Component<{}, {}> {
  private data: componentTypeNameData

  render() {
    return (
      <div>
        <a href='https://github.com/AUTHOR/REPOSITORY_NAME/tree/master/packages/react/demo' target='_blank'>the source code of the demo</a>
        <br />
        <componentTypeName data={this.data}>
        </componentTypeName>
      </div>
    )
  }
}

ReactDOM.render(<Main />, document.getElementById('container'))
